jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Integration Test
      run: mvn compile -B && mvn clean test -DisSkipUnitTest=true "-Dtest.logging.level=ERROR"
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: ScaCap/action-surefire-report@v1
      with:
        fail_on_test_failures: true
        skip_publishing: true
name: integration test
on:
  repository_dispatch:
    types: trigger-ga___integration-test.yml
