jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Unit Testt
      run: mvn compile -B && mvn clean test -DisSkipIntegrationTest=true "-Dtest.logging.level=ERROR"
        --fail-at-end --batch-mode
    - continue-on-error: true
      if: ${{ always() }}
      name: Publish Test Report
      uses: ScaCap/action-surefire-report@v1
      with:
        fail_on_test_failures: true
        skip_publishing: true
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
name: unit test
on:
  repository_dispatch:
    types: trigger-ga___unit-test.yml
